### ISSUE TITLE
rename repository

### ISSUE THREAD

**Issue by professor-enoqueleal** [eolnardo/PI3_Projeto#1]
Turma, por convenção, criamos os nomes de repositório no github utilizando apenas letras minúsculas (lower camel case) e separamos as palavras utilizando hyphen ao invés de underline.

Sugiro fazer o rename do repositório seguindo a convenção de nomeclatura.

Outro ponto, o repositório deve conter o nome do projeto de acordo com o tema escolhido, não o nome da disciplina em questão.

**Comment by eolnardo** [comment]
nome do projeto alterado para "pet-protectors"
